### ISSUE TITLE
Power Junction faces one direction

### ISSUE THREAD

**Issue by justin0a0** [RS485/LogisticsPipes-Deprecated#316]
The power junction block will only face one direction regardless of what direction you are standing in.
in the image stood in the middle and placed in a circle around me. Probably just a trivial fix but not critical in anyway just helps texture packs out

![2012-12-22_13 46 45](https://f.cloud.github.com/assets/123844/28634/bcd84cf8-4c68-11e2-8317-24070147919f.png)

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
