### ISSUE TITLE
Abort button

### ISSUE THREAD

**Issue by ShamblerDK** [RS485/LogisticsPipes-Deprecated#382]
A couple of suggestions:

1: Abort button for when the logistics system fails (IC2 RE-batteries anyone?)
2: Cancel all orders button on the request pipe GUI.
3: Pause button on the request pipe so all items gets frozen in the pipes, both effective and visually, while you debug the system. Make the button able to be activated by a redstone pulse (for use with wireless remote).

Regards,
ShamblerDK

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
