### ISSUE TITLE
Equivelent sorting between same-priority crafting pipes/item sinks

### ISSUE THREAD

**Issue by ErzengelLichtes** [RS485/LogisticsPipes-Deprecated#497]
I have set up several crafting pipes with equivalent priority attached to several machines, all set to output the same thing. I was hoping that when I requested a large number of the result, it would send the components evenly among the same-priority crafting pipes. It did not, instead choosing one apparently at random (they are all of equivalent distance from the request point) and trying to stuff all the components into that one, even if I request so many that it bounces back. This means that I cannot set up long-running processes (like furnaces) to run in parallel if I'm expecting a large number of items in them. I used to be able to do this back before the pipes were able to have priorities.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
