### ISSUE TITLE
Factorization Crystalizer distribution module

### ISSUE THREAD

**Issue by ang-zeyu** [RS485/LogisticsPipes-Deprecated#512]
Currently, my system involves a total of 6 routers, a few buildcraft and logsitics pipes to distribute the reduced chunks evenly amongst the crystalizer. Was wondering if anyone could implement a module that acts as an itemsink and distributes items amongst the crystalizer. ^_^

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests

**Comment by psxlover** [comment]
@bziemons how many tickets are in this outdated Repo?

Btw good to see you are still working on Logistic Pipes :)

**Comment by bziemons** [comment]
@psxlover good to see you! :) Well, 729 issues total as GitHub tells me, but not many left.. I can finally set this repo to rest after I moved the last open ideas
