### ISSUE TITLE
Gates on Chassis, disable pipe per slot

### ISSUE THREAD

**Issue by ErzengelLichtes** [RS485/LogisticsPipes-Deprecated#542]
On a Thermal Expansion Induction Smelter, I have a supplier that is set to input rich slag, and has a gate that emits a red pipe signal if the supplier failed, then on top I have a chassis that has a sink for gold and an extractor set to pull from the bottom, then a gate that says when red pipe signal, disable pipe. The problem is, this disables the whole pipe (except for routing), so as soon as the rich slag runs out it stops pulling out the gold that's being cooked or is already there. 

It would be nice if, for a chassis, there was a "Disable Slot 1", "Disable Slot 2", ... "Disable Slot N" for the number of slots in the chassis. I don't know how well that'll work on a chassis mk 5, I don't think even a diamond gate has enough slots for that.

**Comment by bziemons** [comment]
Superseeded by https://github.com/RS485/LogisticsPipes/issues/1135
