### ISSUE TITLE
ComputerCraft API added to see if a supply request failed

### ISSUE THREAD

**Issue by nekosune** [RS485/LogisticsPipes-Deprecated#543]
Basically wish to have a way for ComputerCraft to know if a supply pipe failed, other then the current way which is to have an iron gate or the like on the pipe, As I wish to have the computer trigger a quarry setup or the like when the supplying of materials to the chest fails.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
