### ISSUE TITLE
[REQUEST] Split Logistics Pipes, Modules, and Tools into separate "Mods" for Mod Based Item Sink

### ISSUE THREAD

**Issue by ErzengelLichtes** [RS485/LogisticsPipes-Deprecated#573]
I understand that you can't really use each part of the mod separately from each other, but if it is possible to make the Mod Based Item Sink think that each category is a different mod, that would be useful. I'm trying to sort APUnoffical, Buildcraft|Transport, and just the pipes from Logistics Pipes into a certain chest. However, I'm also getting modules in the chest from the Mod Based Item Sink.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
