### ISSUE TITLE
Implement a restriction tube equivalent

### ISSUE THREAD

**Issue by vektah** [RS485/LogisticsPipes-Deprecated#605]
Redpower 2 has restriction tubes which for pipe length calculation during routing act as 5000 pieces of tube. This does not slow items down crossing the boundary but is only used for routing costs.

This allows you set up relative weights for central storage vs local storage vs crafting with ACT II's etc by penalizing certain sections of the network.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
