### ISSUE TITLE
Logistics Pipe Mk3 - Advanced Crafting Table Bug Edit

### ISSUE THREAD

**Issue by KThompson77** [RS485/LogisticsPipes-Deprecated#628]
Though the request is formatted as 'successful' in the Request GUI, the items do not in fact respond as extracted by the crafting pipe, and instead as automatic ejection from a finished recipe. As such, the request builds up without ever resulting in the items actually being sent to the request location.

Any recipe require a several-step autocraft process as such fails miserably. Ex: I'm trying to organize my storage, I ask for 20 diamond chests from IronChests mod, the additional raw material is sent to the ACT no issue, but starting at the regular vanilla chest, it all falls apart and never receives the chest for the next tier up, etc etc.

The ACT's ability to access an outside inventory was not specified clearly in the wiki whether this access is an active extraction, or if it requires the items to be pumped from said inventory. As such, I'm assuming the issue lies with the ACT's priority to eject a finished item overriding the crafting pipes priority to extract said item. I ran in to a similar issue when using BetterFurnaces Extreme Furnace for crafting. In large orders, the items would stack up and cycle, but sometimes it would not then re-send the items to finish the request. As such, I attached an extractor in a chassis to handle the excess, but then had a perpetual 'x to go' notification via the Goggles. The chassis extracted before the crafting pipe and prevented it from counting a completed craft.

**Comment by bziemons** [comment]
As far as I understood, part of https://github.com/RS485/LogisticsPipes/issues/255
