### ISSUE TITLE
Ability to check routes from CC peripheral

### ISSUE THREAD

**Issue by Mordenkainen** [RS485/LogisticsPipes-Deprecated#641]
It would be nice to have a peripheral call added to the core pipe to allow computers to check if a particular item could be routed.

Something like:
boolean canItemBeRouted(Double itemID, boolean allowDefault)

itemID is the ItemIdentifier of the item to route and allowDefault is a boolean indication if routing to a default route should be allowed.

There are several cases where this would be useful.
For Example:
- You have a itemsink & provider in a chassis pipe with the provider set to keep a single item in the inventory, this pipe is connected to a Factorization Barrel. When you call getAvailableItems(), this item will NOT be shown (because the single item is suppressed). This prevents the computer for programatically determining if a particular item has a destination on the network when in this state. In this case, you could call the new function, and see that there is a valid destination available for that item.
- This function can return false if all valid destinations have full inventories, allowing the computer to determine if all storage for a given item on the network is used.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
