### ISSUE TITLE
AE Interface can provide to itself

### ISSUE THREAD

**Issue by Sakata-MC** [RS485/LogisticsPipes-Deprecated#698]
The 'buffer' patch for chests should also apply to pipes on the same interface as another pipe.

If you have two AE networks, and have some of the same item on another AE subnet, you cannot reliably request or from the other network as it will pull items from the network the request pipe is connected to (that also has a provider).

**Comment by bziemons** [comment]
To be fixed in AE integration. Today that would be Logistics Bridge.
