### ISSUE TITLE
RFE:  liquids as crafting products

### ISSUE THREAD

**Issue by gholms** [RS485/LogisticsPipes-Deprecated#709]
Right now the best way to provide liquids on demand is by supplying ingredients to liquid-producing machines, hooking liquid providers up to those machines, and relying on production stopping when the machines' internal tanks fill up.  This works to an extent, but it doesn't let one take one's item inventory into account when trying to craft things that require liquids.  For instance, if I request a lot of scented paneling, one of a few things is likely to be the case:
- I have enough liquid honey on hand to satisfy the request
- I do not have enough liquid honey on hand to satisfy the request, but I can make the difference up with honey drops
- I do not have enough liquid honey or honey drops on hand to satisfy the request

Right now there is no way to definitively tell whether a request that involves liquids can be satisfied ahead of time because liquids can't be crafting products -- they can only be ingredients.  I would like to be able to create recipes like this:
- 1 honey drop -> 100 liquid honey
- 100 biomass -> 30 ethanol
- X fruit juice, Y saplings, and Z fertilizer -> W biomass

This would allow liquids to fully participate in crafting trees as both ingredients and products like items can.

**Comment by bziemons** [comment]
Wow marth, 7 years and you haven't gotten fluid crafting and still didn't run away? ;)

Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
