### ISSUE TITLE
Pipe/module installable upgrades instead of MK1-2-3-4-5 things

### ISSUE THREAD

**Issue by target-san** [RS485/LogisticsPipes-Deprecated#729]
Here's idea.
1. Have MK2-3-4-5-whatever-needed special upgrade items, applicable for both pipes and modules
2. Provide per-module upgrades
3. Modules like Provider become MK2-3 when corresponding module is installed
4. Not sure if it would be well-balanced. Leave single type of chassis pipe, making multi-slot ones with upgrades. To balance, require upgrade piece one tier higher than usual.

Pros:
1. Pipes/modules can be upgraded/downgraded in-place, without dropping settings
2. Less items, more combinations in total

Cons:
1. Might require decent amount of coding
2. Smooth migration might be an issue. The only way I see for now is to silently replace MKX things with MK1 and add upgrade module

ADD: liquid logistics pipes could be also implemented as ordinary pipes plus "Liquid Upgrade"

**Comment by bziemons** [comment]
Moved the chassis upgrade part to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
