### ISSUE TITLE
Pipes change selected item for Assembly Tables

### ISSUE THREAD

**Issue by dmarcuse** [RS485/LogisticsPipes-Deprecated#740]
I currently autocraft a good amount of circuits with assembly tables - a satellite on the assembly table to send the resources there, the crafting pipe on the chest where the circuit is output. However, I noticed that, if I set up recipes that use the same resources (Such as letting it make golden chipsets and redstone chipsets; both take redstone) and tell the system to craft 5 golden chipsets, I will end up with three golden chipsets and two redstone chipsets. I was wondering if it would be possible to have the satellite pipe (Since its the one actually connected to the assembly table) detect assembly table, check if the recipe from the crafting pipe, and then deselect all recipes in the crafting table and select the recipe for the output of the crafting pipe.

While I can use multiple assembly tables, the cost builds up over time, and the tables aren't very cheap in the first place.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
