### ISSUE TITLE
Interactive Hud Improvements

### ISSUE THREAD

**Issue by mikeloeven** [RS485/LogisticsPipes-Deprecated#781]
I would like to see the logistics hud become more interactive. currently it lets you see information for all pipe configurations but it's practical uses are limited. i think it would be a great improvement if the hud could have a few more modes for debugging that would let you more closely monitor item paths and even cancel requests or temporarily shut down a problem pipe.

essentially i am not really sure what i want to see added but i would defiantly like to see more debugging features and remote pipe control where the hud lets you actually edit the configurations from a distance or even act as a remote orderer. essentially make it more of an endgame control unit rather than a passive information display

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
