### ISSUE TITLE
Logistics Request Table Enhancements

### ISSUE THREAD

**Issue by PrefeX** [RS485/LogisticsPipes-Deprecated#799]
I have a few feature requests that I hope you will consider to add to the Logistics Request Table to make it easier to use.
1. Item movement features from Vanilla, NEI and Inventory Tweaks is currently not working in the table. As a result, I can't use shift+click, alt+click, shift+alt+click, scrollwheel and/or middle mouse button in the table to move items between the inventory of the player and table. This makes it extremely painfull to request large amount of items for the player to bring along.
2. Despite using an MK2 request pipe in the crafting, the table don't show the thumbcraft aspects.
3. It would be great if the table was split into zones so you could use the mousewheel to change the current item page (in addition to the buttons), amount of items to request (current feature if im not mistaken) and NEI/Inventory Tweaks movement of items between inventorys based on the position of the mouse in the GUI
4. I can't currently use the vanilla feature of holding the left or right mouse button when dragging items into the crafting grid. The system only works with the old behaviour, and it would be great if this feature would work propperly.
5. Would love a way of emptying the table back into the system after use, either with a upgrade/pipe module or as default feature inside the table.
6. Not sure if this is a error with the Request Table and/or the auto crafting system, but when trying to craft (in the request tables crafting grid) or autocraft items in logistic crafting tables, it don't appear to check the ore dictionary (e.g. for for other registered types of wood/planks)
7. Would be great if the table could also access the players inventory for items when doing the crafting.
8. When using the + buttons under the crafting output to request materials, it dosn't take into consideration the materials already in the inventory.
9. I hope you will consider making it possible to use ctrl+backspace on text in the search box

Hope you will consider these features so I can go back to using the request table instead of using a regular request pipe with a 3rd party crafting table to speed up my crafting process.

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
