### ISSUE TITLE
extended computercraft support

### ISSUE THREAD

**Issue by shadoxxhd** [RS485/LogisticsPipes-Deprecated#800]
it seems like there is no way to change the items in the holo slots of logistic pipes with computers. this would be really usefull, for example if you want to make a automatic missile reloading station which changes the loaded missiles on command(adding the loaded missile to a extractor pipe whitelist, and adding the new missile in the supplier pipe whitelist)

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
