### ISSUE TITLE
[Request] Pipe for Liquid Default Route

### ISSUE THREAD

**Issue by Eegras** [RS485/LogisticsPipes-Deprecated#831]
This can currently be done with a Liquid Supplier Pipe but if you add to the liquid storage you have to manually update the pipe.  Furthermore, currently you need a provider pipe on whatever machine or input you have for the Supplier Pipe to work properly which can be undesirable ( and expensive ).  A "Default Route" for liquid pipes would be great.

**Comment by bziemons** [comment]
Dunno how this could be done. There is the usual fluid sink, which just takes one fluid until the attached tank is full
