### ISSUE TITLE
[Feature] let requested crafted items get sorted instead of delivering to request source

### ISSUE THREAD

**Issue by Ealendir** [RS485/LogisticsPipes-Deprecated#859]
Hi Guys,

would it be possible to add a feature that when sending a crafting request to let the crafted items get sorted instead of delivering them to the request table ? 
So that one could craft some items in advance for later use ?

**Comment by bziemons** [comment]
Moved to https://github.com/RS485/LogisticsPipes/wiki/Feature-Requests
