### ISSUE TITLE
Can't find buildcraft 3 smp, or the buildcraft 2 version of this mod for 1.2.5

### ISSUE THREAD

**Issue by logoster** [RS485/LogisticsPipes-Deprecated#867]
yes i am playing with this, can anyone help me find them? none of the old links seem to exist anymore, so the 1.2.5 version of this version of the logistics pipes mod (no i wont use kraphts, because i need SMP) doesn't work as it needs the beta not officially released version of bc3 with SMP for 1.2.5, which isn't actually on buildcrafts website, they only have the SSP version

either that or i need the buildcraft 2 version of this logistics pipes mod, which i also can not find anywhere

**Comment by davboecki** [comment]
Didi you try any version from here: https://ci.rs485.network/view/Logistics%20Pipes%20Archive/job/LogisticsPipesMC1.2.5/

**Comment by logoster** [comment]
yes, it wants buildcraft 3

**Comment by logoster** [comment]
so, no one has any ideas then?

**Comment by davboecki** [comment]
Do you know how to compile Buildcraft yourself, because I could give you the sourcecode of buildcraft, that was used to compile LogisticsPipes, but I don't have a compiled Jar file for that.

**Comment by logoster** [comment]
I do not
